first stage of creating a semi-automated pipeline

diff --git a/bin/episomizer b/bin/episomizer
--- a/bin/episomizer
+++ b/bin/episomizer
@@ -1,3 +1,45 @@
 #!/usr/bin/env bash
 
-composer.py
+EPISOMIZER_HOME=$(dirname $(dirname $(readlink -f $0)))
+if [ -z "$EPISOMIZER_HOME" ]; then
+    echo "Error: EPISOMIZER_HOME is empty" >&2
+    return 1
+    exit 1
+fi
+
+prepend() {
+  echo "$1" | tr : '\n' | awk -v new="`readlink -f $2`$3" 'BEGIN { print new } $0 != new { print }' | tr '\n' : | sed 's/:$//'
+}
+addbin() {
+  if [ -d $1 ]; then NEWPATH=$(prepend "$PATH" "$1"); export PATH="$NEWPATH"; fi
+}
+addpython() {
+  if [ -d $1 ]; then NEWPYTHONPATH=$(prepend "$PYTHONPATH" "$1"); export PYTHONPATH="$NEWPYTHONPATH"; fi
+}
+addperl() {
+  if [ -d $1 ]; then NEWPERL5LIB=$(prepend "$PERL5LIB" "$1"); export PERL5LIB="$NEWPERL5LIB"; fi
+}
+
+addpython $EPISOMIZER_HOME/lib/python
+addbin $EPISOMIZER_HOME/bin
+
+usage() {
+   echo "Usage:"
+   echo "    episomizer <SUBCOMMAND> [args...]"
+   echo "Subcommands:"
+   echo "    create_samtools_cmd   Create samtools command file to extract reads around boundaries of CNA segments"
+   exit 1
+}
+
+if [ "$#" == 0 ]; then
+    usage
+    return 1
+    exit 1
+fi
+
+SUBCOMMAND=$1
+
+case $SUBCOMMAND in
+    create_samtools_cmd) ${SUBCOMMAND}.pl ${@:2} ;;
+    *) usage ;;
+esac
